#  ____                     __ _ _
# | __ ) _ __ _____      __/ _(_) | ___
# |  _ \| '__/ _ \ \ /\ / / |_| | |/ _ \
# | |_) | | |  __/\ V  V /|  _| | |  __/
# |____/|_|  \___| \_/\_/ |_| |_|_|\___|

cask_args appdir: '/Applications'

tap 'homebrew/cask-fonts'
tap 'homebrew/bundle'
tap 'homebrew/services'

brew 'archey4'
brew 'autojump'
brew 'awscli'
brew 'direnv'
brew 'exiftool'
brew 'figlet'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'git-extras'
brew 'htop'
brew 'httpie'
brew 'mas'
brew 'mysql'
brew 'neovim'
brew 'node-build'
brew 'nodenv'
brew 'node'
brew 'pinentry-mac'
brew 'postgresql'
brew 'rbenv'
brew 'readline'
brew 'ripgrep'
brew 'ruby-build'
brew 'shellcheck'
brew 'starship'
brew 'tig'
brew 'thefuck'
brew 'the_silver_searcher'
brew 'tmux'
brew 'trash'
brew 'tree'
# brew 'zplug' # Maybe start using this https://github.com/zplug/zplug
brew 'zsh'
brew 'bat'

cask '1password'
cask '1password-cli'
cask 'android-studio'
cask 'alfred'
cask 'authy'
cask 'cyberduck'
cask 'datagrip'
cask 'discord'
cask 'dropbox'
cask 'docker'
cask 'expressvpn'
cask 'firefox'
cask 'homebrew/cask-versions/firefox-developer-edition'
cask 'font-courier-prime-code'
cask 'font-fira-code'
cask 'font-source-code-pro'
cask 'font-cascadia-code'
cask 'font-caskaydia-cove-nerd-font'
cask 'gitup'
cask 'google-chrome'
cask 'gpg-suite'
# cask 'hazel'
cask 'iterm2'
cask 'little-snitch'
cask 'postman'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'slack'
cask 'sonos'
cask 'spotify'
cask 'the-unarchiver'
cask 'tor-browser'
cask 'visual-studio-code'
cask 'vlc'
cask 'xld'
cask 'zoom'

mas 'amphetamine', id: 937984704
mas 'focus to-do', id: 1258530160
mas 'moom', id: 419330170
mas 'xcode', id: 497799835
