cask_args appdir: '/Applications'

tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

# Apps
cask 'iterm2'
cask 'visual-studio-code'
cask 'sublime-text'
cask 'gpg-suite'
cask 'alred'
cask 'firefox'
cask 'google-chrome'
cask 'datagrip'
cask 'dropbox'
cask 'docker'
cask 'evernote'
cask 'virtualbox'
cask 'spotify'
cask 'signal'
cask 'vlc'
cask 'little-snitch'
cask 'the-unarchiver'

# Developer Utilities
brew 'git'
brew 'ruby-build'
brew 'rbenv'
brew 'node-build'
brew 'nodenv'
brew 'node'
brew 'postgresql'
brew 'mysql'
brew 'heroku-toolbelt'

# CLI Tools
brew 'tmux'
brew 'the_silver_searcher'
brew 'tree'
brew 'readline'
brew 'autojump'
brew 'fzf'
brew 'neovim'
