# https://starship.rs/config

format = "[$all](bold 15)"
add_newline = false

[hostname]
format =  "[$hostname](11) in "

[username]
format = "[$user](9) on "

[package]
disabled = true

[git_branch]
style = "bold 75"
