# https://starship.rs/config

format = "[$time$all](bold 15)"
add_newline = false

[hostname]
format =  "on [$hostname](11) "

[username]
format = "as [$user](9) "

[package]
disabled = true

[git_branch]
style = "bold 75"

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "

[time]
disabled = false
time_format = "%R"
style = "bold 13"

[nodejs]
symbol = '🤖 '

[ruby]
symbol = '💎 '
